dependencies:
- name: beedemo-ops-go-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: johns2te-go-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: kmadel-go-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: lcorbo-cb-go-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: ldonley-go-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mcgonagle-go-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mdelgin-go-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: philcgithub-go-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
